### ISSUE TITLE
--without option not working

### ISSUE THREAD

**Issue by domofactor** [wercker/step-bundle-install#9]
I've been trying to bundle install without certain groups, but they still get installed anyways it seems. Thanks!

```
wercker version 1.0.389 (Compiled at: 2016-01-25T18:26:21Z, Git commit: b1087969fc9cbce345142b87e7dbb6b0eead8670)
```

```
Installing kitchen-docker 2.3.0
Installing kitchen-ec2 0.10.0
Installing powerpack 0.1.1
Installing rainbow 2.0.0
Installing ruby-progressbar 1.7.5
Installing tins 1.6.0
Installing rubocop 0.35.1
Using bundler 1.10.6
Bundle complete! 7 Gemfile dependencies, 76 gems now installed.
Gems in the groups berkshelf, style, unit and kitchen_docker were not installed.
Bundled gems are installed into /pipeline/cache/bundle-install.
finished bundle install --path /pipeline/cache/bundle-install/ --without berkshelf style unit kitchen_docker
```

```
build:
  steps:
    - install-packages:
        packages: autoconf
    - bundle-install:
        without: berkshelf style unit kitchen_docker
```
